=== christopherchristensen/wg-xml/project/data/contest.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="contests">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="contest"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="contest">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element name="name" type="contestNameType"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="company" type="companyType"/>
                <xs:element name="startDate" type="xs:date"/>
                <xs:element name="endDate" type="xs:date"/>
                <xs:element ref="votes" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="votes">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="vote"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="vote">
        <xs:complexType> <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="wg" type="xs:string" />
            </xs:extension> </xs:simpleContent>
        </xs:complexType>
    </xs:element>


    <!-- custom DataTypes -->

    <xs:simpleType name="contestNameType">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="companyType">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== christopherchristensen/wg-xml/project/data/contest.xml
<?xml version="1.0" ?>
<contests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="contest.xsd">
    <contest>
        <name>Test</name>
        <description>Test</description>
        <company>Test</company>
        <startDate>2019-02-01</startDate>
        <endDate>2019-03-01</endDate>
        <votes>
            <vote wg="1">3</vote>
        </votes>
    </contest>
</contests>
